# Describes the format for available climate services

set_away_mode:
  description: Turn away mode on/off for climate device.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'climate.kitchen'
    away_mode:
      description: New value of away mode.
      example: true
set_hold_mode:
  description: Turn hold mode for climate device.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'climate.kitchen'
    hold_mode:
      description: New value of hold mode
      example: 'away'
set_temperature:
  description: Set target temperature of climate device.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'climate.kitchen'
    temperature:
      description: New target temperature for HVAC.
      example: 25
    target_temp_high:
      description: New target high tempereature for HVAC.
      example: 26
    target_temp_low:
      description: New target low temperature for HVAC.
      example: 20
    operation_mode:
      description: Operation mode to set temperature to. This defaults to current_operation mode if not set, or set incorrectly.
      example: 'Heat'
set_fan_mode:
  description: Set fan operation for climate device.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'climate.nest'
    fan_mode:
      description: New value of fan mode.
      example: On Low
set_operation_mode:
  description: Set operation mode for climate device.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'climate.nest'
    operation_mode:
      description: New value of operation mode.
      example: Heat
set_swing_mode:
  description: Set swing operation for climate device.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'climate.nest'
    swing_mode:
      description: New value of swing mode.

turn_on:
  description: Turn climate device on.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'climate.kitchen'

turn_off:
  description: Turn climate device off.
  fields:
    entity_id:
      description: Name(s) of entities to change.
      example: 'climate.kitchen'